### ISSUE TITLE
[US] User can view a dashboard that renders a collection tags

### ISSUE THREAD

**Issue by sojour** [tag-digital-graffiti/TagAR#17]
- [ ] Create a Home/dashboard component #35
- [ ] Create a Nav Bar #34
- [ ] Use React Navigation to route pages #34
