### ISSUE TITLE
Subtask #12 - Users can select from nearby tags to view in AR

### ISSUE THREAD

**Issue by MadelineEmde** [tag-digital-graffiti/TagAR#22]
- [ ] Use React Native FlatList to create grid view
- [ ] On Click will update selected tag in Redux Store 
- [ ] On Click will connect each tag to AR view component
